version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
    overwrite: true

hooks:
  BeforeInstall:
    - location: scripts/clean.sh
      timeout: 60
      runas: root

  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 60
      runas: root
