version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Cleaning npm cache..."
      - rm -rf node_modules package-lock.json
      - npm cache clean --force
      - echo "Installing dependencies..."
      - npm install   

  build:
    commands:
      - echo "Building React app..."
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: "./"
