version: 0.2

env:
  variables:
    BUILD_DIR: "dist"
    NGINX_DIR: "/var/www/html"

cache:
  paths:
    - '/root/.npm/**/*'

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - set -e
      - echo "Using Node.js $(node -v) and npm $(npm -v)"

  pre_build:
    commands:
      - echo "Cleaning npm cache & removing existing dependencies..."
      - rm -rf node_modules package-lock.json
      - npm cache clean --force

  build:
    commands:
      - echo "Installing frontend dependencies..."
      - npm install
      - echo "Building frontend..."
      - npm run build

  post_build:
    commands:
      - echo "Deploying frontend to Nginx..."
      - sudo rm -rf $NGINX_DIR/*
      - sudo cp -r $BUILD_DIR/* $NGINX_DIR/
      - echo "Deployment completed at $(date)"

artifacts:
  files:
    - '**/*'
  base-directory: dist
